name: declanorourke
favicon: null
layout_spectrum: 0.74736
typography_spectrum: 1
title: Declan O' Rourke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.9650043547153473
  saturation: 0.8852920988574624
  rhythmicContrast: 0.9436395324300975
purpose: []
